//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerFaravin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messageRecipient
    {
        public int id { get; set; }
        public int message_id { get; set; }
        public Nullable<int> userReceiver_id { get; set; }
        public Nullable<int> groupReceiver_id { get; set; }
    
        public virtual group group { get; set; }
        public virtual message message { get; set; }
        public virtual user user { get; set; }
    }
}
