//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerFaravin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class faravinEntities1 : DbContext
    {
        public faravinEntities1()
            : base("name=faravinEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contacts> contacts { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<groupsUsers> groupsUsers { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<messageRecipient> messageRecipient { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
