//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerFaravin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public message()
        {
            this.message1 = new HashSet<message>();
            this.messageRecipient = new HashSet<messageRecipient>();
        }
    
        public int id { get; set; }
        public int sender_id { get; set; }
        public string subject { get; set; }
        public string messageText { get; set; }
        public System.DateTime sendDate { get; set; }
        public System.DateTime sendTime { get; set; }
        public Nullable<int> parentMessage_id { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> message1 { get; set; }
        public virtual message message2 { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messageRecipient> messageRecipient { get; set; }
    }
}
